development:
  adapter: postgresql
  encoding: UTF-8
  database: final_heroku_development
  pool: 5
  username: ericm
  password: password1

test:
  adapter: postgresql
  encoding: UTF-8
  database: final_heroku_test
  pool: 5
  username: ericm
  password: password1
