development:
  adapter: postgresql
  encoding: UTF-8
  database: myapp_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: UTF-8
  database: myapp_test
  pool: 5
  username:
  password: 
