Place.delete_all
Place.create(:title => "Summer Palace", :price => "483", :description=> "Once a summer retreat for emperors, this 290-acre park is still a retreat for the crowd-weary tourist, who can relax here or stroll around ancient pavilions, mansions, temples, bridges and huge lake, stopping occasionally at a shop or tea-house." , :photourl => "http://cache.wallpaperdownloader.com/bing/img/BeijingSummerPalace_20130801.jpg")
#Place.create(:title => "" , :price => "", :description => "" , :photourl => "")
Place.create(:title => "Forbidden City" , :price => "966", :description => "Lying at the city center and called Gu Gong in Chinese, it was the imperial palace for twenty-four emperors during the Ming and Qing dynasties. It was first built throughout 14 years during the reign of Emperor Chengzu  in the Ming Dynasty (1368-1644). Ancient Chinese Astronomers believed that the Purple Star (Polaris) was in the center of heaven and the Heavenly Emperor lived in the Purple Palace. The Palace for the emperor on earth was so called the Purple City. It was forbidden to enter without special permission of the empeor. Hence its name The Purple Forbidden City, usually The Forbidden City." , :photourl => "http://www.wallallies.com/wp-content/uploads/2015/03/Forbidden-City-Aerial-View-13-HD-Wallpaper.jpg")
Place.create(:title => "Temple of Heaven" , :price => "242", :description => "The Temple of Heaven Park is located in the Chongwen District, Beijing. Originally, this was the place where emperors of the Ming Dynasty (1368 - 1644) and Qing Dynasty (1644 - 1911) held the Heaven Worship Ceremony. It is China's largest and most representative existing masterpiece among China’s ancient sacrificial buildings. First built in 1420, the 18th year of the reign of Emperor Yongle of the Ming Dynasty (1368 - 1644), it was enlarged and rebuilt during the reigns of the Ming emperor Jiajing and the Qing emperor Qianlong. In 1988, it was opened to the public as a park, showing ancient philosophy, history and religion. Its grand architectural style and profound cultural connotation give an insight into the practices of the ancient Eastern civilization." , :photourl => "http://www.beijingcentre.com/Beijing-Travel-Information/Beijing-Serviced-Apartments-Temple-of-Heaven/Temple2.jpg")
Place.create(:title => "Badaling great wall" , :price => "725", :description => "The Great Wall is a symbol of Chinese civilization, and one of the wonders that the Chinese people have created. Badaling Great Wall, the most representative part, was promoted as a key national cultural relic, protected under the approval of the State Council in 1961. In 1988, it was enlisted in the World Cultural Heritage Directory by UNESCO. On July 7, 2007, it gained the worldwide reputation once again: it was listed among the New Seven Wonders of the World." , :photourl => "http://www.paulnoll.com/China/Tourism/Great-Wall-Badaling-2.jpg")
Place.create(:title => "Fragrant Hills Park" , :price => "161", :description => "Situated in the east part of western hills, 28 kilometers (17 miles) northwest of the city, it is very large, made up of hills and forest covering 160 hectares (395.4 acres). Both its natural sceneries and cultural relics are abundant. Xianglu Peak (Incense Burner Peak), 557 meters (1827.4 feet) high, is its highest peak. It was first built in 1186 in the Jin Dynasty (1115-1234) and later extended to a large scale in the Yuan and Ming dynasties. In 1745, Emperor Qianlong (1711-1799) ordered the addition of many new halls, pavilions and gardens and gave it a new name, Jingyi Garden (Garden of Tranquility and Pleasure). Unfortunately, in 1860 and 1900 after the Summer Palace and the Yuanming Yuan (the Old Summer Palace) were set on fire, lots of relics in the Fragrant Hills were damaged by foreign troops. Since 1949, with a half-century's restoration and development by Chinese government, it has been recognized as one of the ten most famous parks in Beijing." , :photourl => "http://www.51qilv.com/data/uploads/2012/0716/17/5003dc43808ab.jpg")
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
